email.origen=greenbuildingcontact@gmail.com
email.password=ymet eoaj bzpz juhq
email.smtp.host=smtp.gmail.com
email.smtp.port=587
multa.monto.defecto=150000
solicitud.alta.dias.limite=3
solicitud.media.dias.limite=7
solicitud.baja.dias.limite=15
login.intentos.maximos=3
superadmin.username=superadmin
superadmin.contrasena=GreenBuilding2026*
superadmin.id=USR-0
cuota.admin.dias.limite=10
multa.dias.limite=30
reserva.max.por.mes=3
reserva.horas.anticipacion.minima=2
reserva.horas.cancelacion.sin.multa=12
